version: '3.8'

services:
  bird-api:
    build:
      context: ./bird
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    depends_on:
      - bird-image-api

  bird-image-api:
    build:
      context: ./birdImage
      dockerfile: Dockerfile
    ports:
      - "4200:4200"